name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Docker Build & Push Action            
      uses: mr-smithers-excellent/docker-build-push@v6.4  
      with:
        image: repo/image
        tags: latest
        registry: docker.io
        dockerfile: docker/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
